### PR TITLE
[ECO-610]: Implement metrics of Clarity with the help of Prometheus

### PR DESCRIPTION
**Pull request by AbnerZheng**
### Overview
This PR adds some metrics for Clarity by using Prometheus. The server would expose an endpoint `/metrics` so that `Prometheus` could pull metrics. 

#### Metrics Details

1. faucet_request_total
type: counter
every time the user does the faucet request, the counter will increase by 1.

2. deploy_request_total
type: counter
every time the user deploys the smart contract from Clarity, the counter will increase by 1.

3. account_key_total
type: gauge
total number of users created keys.

4. user_account_total
type: gauge
the total number of users signed up.

5. daily_login_days
type: gauge
the total number of login users each day.

6. daily_signup_days
type: gauge
the total number of sign up each day. 

Here is the example content when visiting the endpoint:

```
# HELP faucet_request_total Count of faucet requests
# TYPE faucet_request_total counter
faucet_request_total 0

# HELP deploy_request_total Count of deploy requests
# TYPE deploy_request_total counter
deploy_request_total 2

# HELP account_key_total Count of account key
# TYPE account_key_total gauge
account_key_total 638

# HELP user_account_total Count of user account
# TYPE user_account_total gauge
user_account_total 464

# HELP daily_login_days Number of logins every day
# TYPE daily_login_days gauge
daily_login_days 3

# HELP daily_signup_days Number of sign up every day
# TYPE daily_signup_days gauge
daily_signup_days 1
```

### Which JIRA ticket does this PR relate to?

_Add the link here. Create a ticket and link it here if one does not exist._

### Complete this checklist before you submit this PR

- [ ] This PR contains no more than 200 lines of code, excluding test code.
- [ ] This PR meets [CasperLabs coding standards](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/16842753/Coding+Standards).
- [ ] If this PR adds a new feature, it includes tests related to this feature.
- [ ] You assigned one person to review this PR.
- [ ] Your GitHub account is linked with our [Drone CI](https://drone-auto.casperlabs.io/) system. This is necessary to run tests on this PR.
- [ ] Do not forget to run `bors r+` if GitHub policy is not enforced, e.g. when merging into another feature branch. It may be omitted under some circumstances if this PR intentionally assumes that integration tests will fail but will be fixed with the future PRs.

### Notes

_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._

### CODE REVIEW

**Review by arcolife — COMMENTED** [review]
`daily_login_days` is this for distinct logins ? or N logins per same user count too? 

PS: branch appears to have a conflicted file

**Comment by AbnerZheng** [comment]
@arcolife ~~`daily_login_days` is for distinct logins.~~

I was wrong, it counts N logins per same user. And I get these metrics from Auth0, here is their answer:

https://community.auth0.com/t/how-is-this-number-of-login-counts-calculated/7937

And the related API document is: https://auth0.com/docs/api/management/v2#!/Stats/get_daily

**Comment by arcolife** [comment]
Alright. I'm not sure on the ROI we're looking for from these metrics (cc/ @piotr-dziubecki ), i.e, if we plan to expand the list above, but I guess google analytics and the likes should cover those.

So LGTM for now!

**Review by arcolife — APPROVED** [review]

**Comment by sacherjj** [comment]
bors r+
Ashok wanted me to merge this as Abner is asleep.

**Pull request merged**
